//! Optional build-acceleration setup for local development.
//!
//! Detects build accelerators, then writes a per-repository Cargo config
//! only when explicitly requested by the user.

use std::fs;
use std::path::Path;
use std::process::Command;

#[derive(Clone, Debug)]
pub struct BuildAccelDetection {
    pub sccache_installed: bool,
    pub mold_installed: bool,
    pub config_status: BuildAccelConfigStatus,
}

#[derive(Clone, Debug)]
pub enum BuildAccelConfigStatus {
    Missing,
    Managed { wrapper_present: bool },
    Unmanaged,
    ReadFailed(String),
}

#[derive(Clone, Debug)]
pub enum BuildAccelOutcome {
    SkippedMissingTools,
    SkippedExistingConfig,
    Written {
        relative_path: String,
        used_sccache: bool,
        used_mold: bool,
    },
    UpdatedExisting {
        relative_path: String,
        used_sccache: bool,
        used_mold: bool,
    },
    Failed(String),
}

pub fn detect_build_accel(repo_root: &Path) -> BuildAccelDetection {
    BuildAccelDetection {
        sccache_installed: command_exists("sccache"),
        mold_installed: command_exists("mold"),
        config_status: detect_build_accel_config_status(repo_root),
    }
}

pub fn detect_build_accel_without_repo(reason: String) -> BuildAccelDetection {
    // Tool detection still works without the repo root, but config status is unknown.
    BuildAccelDetection {
        sccache_installed: command_exists("sccache"),
        mold_installed: command_exists("mold"),
        config_status: BuildAccelConfigStatus::ReadFailed(reason),
    }
}

pub fn write_build_accel_config(
    repo_root: &Path,
    detection: &BuildAccelDetection,
) -> BuildAccelOutcome {
    // Keep build-acceleration changes scoped to this repository.
    let config_path = repo_root.join(".cargo").join("config.toml");
    let wrapper_path = repo_root.join(".cargo").join("unixnotis-rustc-wrapper.sh");
    if config_path.exists() {
        // Update installer-managed configs to the safe wrapper format,
        // even if accelerators are currently missing.
        return update_existing_config(&config_path, &wrapper_path, detection);
    }

    // Skip when neither accelerator is present to avoid unnecessary wrapper setup.
    if !detection.sccache_installed && !detection.mold_installed {
        return BuildAccelOutcome::SkippedMissingTools;
    }

    let content = format_build_accel_config();

    if let Some(parent) = config_path.parent() {
        if let Err(err) = fs::create_dir_all(parent) {
            return BuildAccelOutcome::Failed(err.to_string());
        }
    }
    if let Err(err) = fs::write(&config_path, content) {
        return BuildAccelOutcome::Failed(err.to_string());
    }
    if let Err(err) = write_wrapper_script(&wrapper_path) {
        return BuildAccelOutcome::Failed(err);
    }

    BuildAccelOutcome::Written {
        relative_path: ".cargo/config.toml".to_string(),
        used_sccache: detection.sccache_installed,
        used_mold: detection.mold_installed,
    }
}

fn format_build_accel_config() -> String {
    // Wrapper script keeps builds working if accelerators are removed later.
    let lines: Vec<String> = vec![
        "# Optional build acceleration for UnixNotis.".to_string(),
        "# Generated by unixnotis-installer; delete to disable.".to_string(),
        "# Wrapper falls back to rustc if accelerators are unavailable.".to_string(),
        String::new(),
        "[build]".to_string(),
        "rustc-wrapper = \".cargo/unixnotis-rustc-wrapper.sh\"".to_string(),
        String::new(),
    ];

    lines.join("\n")
}

fn update_existing_config(
    config_path: &Path,
    wrapper_path: &Path,
    detection: &BuildAccelDetection,
) -> BuildAccelOutcome {
    let existing = match fs::read_to_string(config_path) {
        Ok(existing) => existing,
        Err(err) => {
            return BuildAccelOutcome::Failed(format!(
                "Failed to read existing build config: {err}"
            ))
        }
    };
    if !existing.contains("Generated by unixnotis-installer") {
        return BuildAccelOutcome::SkippedExistingConfig;
    }

    // Rewriting installer-owned configs keeps local builds resilient
    // when sccache or mold are removed after initial setup.
    let content = format_build_accel_config();

    if let Err(err) = fs::write(config_path, content) {
        return BuildAccelOutcome::Failed(err.to_string());
    }
    if let Err(err) = write_wrapper_script(wrapper_path) {
        return BuildAccelOutcome::Failed(err);
    }

    BuildAccelOutcome::UpdatedExisting {
        relative_path: ".cargo/config.toml".to_string(),
        used_sccache: detection.sccache_installed,
        used_mold: detection.mold_installed,
    }
}

fn detect_build_accel_config_status(repo_root: &Path) -> BuildAccelConfigStatus {
    // Config status is derived from installer markers and wrapper presence.
    let config_path = repo_root.join(".cargo").join("config.toml");
    if !config_path.exists() {
        return BuildAccelConfigStatus::Missing;
    }

    let content = match fs::read_to_string(&config_path) {
        Ok(content) => content,
        Err(err) => return BuildAccelConfigStatus::ReadFailed(err.to_string()),
    };

    if !content.contains("Generated by unixnotis-installer") {
        return BuildAccelConfigStatus::Unmanaged;
    }

    let wrapper_path = repo_root.join(".cargo").join("unixnotis-rustc-wrapper.sh");
    BuildAccelConfigStatus::Managed {
        wrapper_present: wrapper_path.exists(),
    }
}

fn write_wrapper_script(wrapper_path: &Path) -> Result<(), String> {
    if let Some(parent) = wrapper_path.parent() {
        fs::create_dir_all(parent).map_err(|err| err.to_string())?;
    }
    fs::write(wrapper_path, wrapper_script()).map_err(|err| err.to_string())?;
    set_wrapper_permissions(wrapper_path).map_err(|err| err.to_string())?;
    Ok(())
}

fn wrapper_script() -> String {
    [
        "#!/usr/bin/env sh",
        "# UnixNotis build accelerator wrapper.",
        "# Routes builds through sccache/mold when available.",
        "# Falls back to rustc when accelerators are missing.",
        "# Clippy is forwarded directly to avoid argument conflicts.",
        "",
        "set -e",
        "",
        "COMPILER=\"$1\"",
        "shift",
        "",
        "case \"$COMPILER\" in",
        "  *clippy-driver*)",
        "    RUSTC=\"$1\"",
        "    shift",
        "    exec \"$COMPILER\" \"$RUSTC\" \"$@\"",
        "    ;;",
        "esac",
        "",
        "RUSTC=\"$COMPILER\"",
        "",
        "if command -v sccache >/dev/null 2>&1; then",
        "  if command -v mold >/dev/null 2>&1; then",
        "    exec sccache \"$RUSTC\" -C link-arg=-fuse-ld=mold \"$@\"",
        "  fi",
        "  exec sccache \"$RUSTC\" \"$@\"",
        "fi",
        "",
        "if command -v mold >/dev/null 2>&1; then",
        "  exec \"$RUSTC\" -C link-arg=-fuse-ld=mold \"$@\"",
        "fi",
        "",
        "exec \"$RUSTC\" \"$@\"",
        "",
    ]
    .join("\n")
}

#[cfg(unix)]
fn set_wrapper_permissions(wrapper_path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;

    let mut perms = fs::metadata(wrapper_path)?.permissions();
    // Ensure the wrapper can be executed by the current user.
    perms.set_mode(0o755);
    fs::set_permissions(wrapper_path, perms)
}

#[cfg(not(unix))]
fn set_wrapper_permissions(_wrapper_path: &Path) -> std::io::Result<()> {
    Ok(())
}

fn command_exists(program: &str) -> bool {
    Command::new("sh")
        .arg("-c")
        .arg(format!("command -v {program} >/dev/null 2>&1"))
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::{
        detect_build_accel_config_status, format_build_accel_config, wrapper_script,
        BuildAccelConfigStatus,
    };
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_dir(prefix: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let mut path = std::env::temp_dir();
        path.push(format!("{prefix}-{nanos}"));
        fs::create_dir_all(&path).expect("temp dir");
        path
    }

    #[test]
    fn format_config_points_to_wrapper() {
        let config = format_build_accel_config();
        assert!(config.contains("rustc-wrapper = \".cargo/unixnotis-rustc-wrapper.sh\""));
        assert!(config.contains("Generated by unixnotis-installer"));
    }

    #[test]
    fn wrapper_script_includes_fallbacks() {
        let script = wrapper_script();
        assert!(script.contains("sccache"));
        assert!(script.contains("mold"));
        assert!(script.contains("clippy-driver"));
        assert!(script.contains("exec \"$RUSTC\" \"$@\""));
    }

    #[test]
    fn config_status_reports_missing_when_absent() {
        let dir = temp_dir("unixnotis-config-missing");
        let status = detect_build_accel_config_status(&dir);
        assert!(matches!(status, BuildAccelConfigStatus::Missing));
        fs::remove_dir_all(&dir).expect("cleanup");
    }

    #[test]
    fn config_status_reports_unmanaged() {
        let dir = temp_dir("unixnotis-config-unmanaged");
        let cargo_dir = dir.join(".cargo");
        fs::create_dir_all(&cargo_dir).expect("cargo dir");
        fs::write(cargo_dir.join("config.toml"), "[build]").expect("config");
        let status = detect_build_accel_config_status(&dir);
        assert!(matches!(status, BuildAccelConfigStatus::Unmanaged));
        fs::remove_dir_all(&dir).expect("cleanup");
    }

    #[test]
    fn config_status_reports_managed_and_wrapper_missing() {
        let dir = temp_dir("unixnotis-config-managed");
        let cargo_dir = dir.join(".cargo");
        fs::create_dir_all(&cargo_dir).expect("cargo dir");
        fs::write(
            cargo_dir.join("config.toml"),
            "# Generated by unixnotis-installer",
        )
        .expect("config");
        let status = detect_build_accel_config_status(&dir);
        assert!(matches!(
            status,
            BuildAccelConfigStatus::Managed {
                wrapper_present: false
            }
        ));
        fs::remove_dir_all(&dir).expect("cleanup");
    }
}
