[package]
name = "unixnotis-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gtk.workspace = true
notify.workspace = true
tracing.workspace = true
unixnotis-core = { path = "../unixnotis-core" }
serde.workspace = true
shell-words.workspace = true
serde_json.workspace = true
url.workspace = true

[[bin]]
name = "unixnotis-css-validate"
path = "src/bin/css_validate.rs"
test = false
