//! Stable layout values exposed to compatible custom themes

pub(super) const fn layout_tokens() -> &'static [(&'static str, &'static str)] {
    // These numbers match shipped layout defaults without requiring themes to scrape stock CSS
    &[
        (
            "--unixnotis-ui-font-family",
            r#""Inter", "SF Pro Text", "Noto Sans", sans-serif"#,
        ),
        (
            "--unixnotis-monospace-font-family",
            r#""CaskaydiaCove Nerd Font Mono", "JetBrains Mono", monospace"#,
        ),
        ("--unixnotis-panel-radius", "30px"),
        ("--unixnotis-panel-padding", "16px"),
        ("--unixnotis-panel-header-radius", "18px"),
        ("--unixnotis-panel-header-padding", "12px"),
        ("--unixnotis-panel-card-padding-y", "9px"),
        ("--unixnotis-panel-card-padding-x", "11px"),
        ("--unixnotis-panel-card-gap", "8px"),
        ("--unixnotis-panel-action-gap", "6px"),
        ("--unixnotis-panel-close-size", "28px"),
        ("--unixnotis-panel-search-min-height", "34px"),
        ("--unixnotis-panel-search-padding-x", "10px"),
        ("--unixnotis-notification-card-radius", "14px"),
        ("--unixnotis-notification-action-padding-y", "4px"),
        ("--unixnotis-notification-action-padding-x", "10px"),
        ("--unixnotis-popup-stack-padding", "8px"),
        ("--unixnotis-popup-card-radius", "18px"),
        ("--unixnotis-popup-card-padding-y", "12px"),
        ("--unixnotis-popup-card-padding-x", "14px"),
        ("--unixnotis-popup-actions-gap", "6px"),
        ("--unixnotis-popup-close-size", "24px"),
        ("--unixnotis-popup-reveal-duration", "200ms"),
        ("--unixnotis-quick-slider-radius", "18px"),
        ("--unixnotis-quick-slider-padding-y", "8px"),
        ("--unixnotis-quick-slider-padding-x", "12px"),
        ("--unixnotis-quick-slider-icon-size", "32px"),
        ("--unixnotis-quick-slider-knob-size", "16px"),
        ("--unixnotis-toggle-min-width", "104px"),
        ("--unixnotis-toggle-min-height", "56px"),
        ("--unixnotis-toggle-padding-y", "10px"),
        ("--unixnotis-toggle-padding-x", "12px"),
        ("--unixnotis-stat-card-radius", "18px"),
        ("--unixnotis-stat-card-min-height", "56px"),
        ("--unixnotis-stat-card-padding-y", "10px"),
        ("--unixnotis-stat-card-padding-x", "12px"),
        ("--unixnotis-info-card-min-height", "56px"),
        ("--unixnotis-info-card-padding", "12px"),
        ("--unixnotis-info-card-radius", "22px"),
        ("--unixnotis-calendar-radius", "18px"),
        ("--unixnotis-media-container-gap", "10px"),
        ("--unixnotis-media-row-gap", "6px"),
        ("--unixnotis-media-control-gap", "6px"),
        ("--unixnotis-media-action-rail-gap", "8px"),
        ("--unixnotis-media-card-padding-y", "8px"),
        ("--unixnotis-media-card-padding-x", "10px"),
        ("--unixnotis-media-card-padding-inline-y", "10px"),
        ("--unixnotis-media-card-padding-inline-x", "12px"),
        ("--unixnotis-media-card-padding-stacked", "12px"),
        ("--unixnotis-media-card-padding-showcase-y", "10px"),
        ("--unixnotis-media-card-padding-showcase-x", "12px"),
        ("--unixnotis-media-art-size", "50px"),
        ("--unixnotis-media-art-frame-size", "54px"),
        ("--unixnotis-media-button-padding-y", "4px"),
        ("--unixnotis-media-button-padding-x", "6px"),
        ("--unixnotis-media-nav-size", "22px"),
        ("--unixnotis-media-nav-radius", "12px"),
        ("--unixnotis-media-nav-font-size", "12px"),
        ("--unixnotis-media-card-radius", "18px"),
        ("--unixnotis-media-card-min-height", "68px"),
        ("--unixnotis-media-card-inline-min-height", "88px"),
        ("--unixnotis-media-card-stacked-min-height", "108px"),
        ("--unixnotis-media-card-showcase-min-height", "92px"),
        ("--unixnotis-media-art-radius", "12px"),
        ("--unixnotis-media-art-frame-radius", "14px"),
        ("--unixnotis-media-source-font-size", "11px"),
        ("--unixnotis-media-source-letter-spacing", "0.1em"),
        ("--unixnotis-media-position-font-size", "11px"),
        ("--unixnotis-media-position-letter-spacing", "0.08em"),
        ("--unixnotis-media-title-font-size", "13px"),
        ("--unixnotis-media-title-font-weight", "700"),
        ("--unixnotis-media-artist-font-size", "12px"),
        ("--unixnotis-media-button-radius", "10px"),
    ]
}
