use std::collections::BTreeMap;
use std::path::PathBuf;

use super::super::bundle::{
    append_generated_assets, validate_transformed_bundle, validate_transformed_bundle_limits,
};
use super::support::bundle_file;
use crate::preset::archive::{MAX_PRESET_PAYLOAD_FILES, MAX_PRESET_TOTAL_PAYLOAD_BYTES};

#[test]
fn generated_asset_collision_requires_identical_non_executable_content() {
    let generated = BTreeMap::from([(
        PathBuf::from("assets/.validated-css/image.png"),
        b"validated".to_vec(),
    )]);
    let mut matching = vec![bundle_file(
        "assets/.validated-css/image.png",
        b"validated".to_vec(),
    )];

    append_generated_assets(&mut matching, &[], generated.clone())
        .expect("accept an identical non-executable generated asset");
    assert_eq!(matching.len(), 1);

    let mut different = vec![bundle_file(
        "assets/.validated-css/image.png",
        b"different".to_vec(),
    )];
    let different_error = append_generated_assets(&mut different, &[], generated.clone())
        .expect_err("reject conflicting generated bytes");
    assert!(different_error.to_string().contains("conflicts"));

    let mut executable = vec![bundle_file(
        "assets/.validated-css/image.png",
        b"validated".to_vec(),
    )];
    executable[0].mode = 0o755;
    let executable_error = append_generated_assets(&mut executable, &[], generated)
        .expect_err("reject executable generated-path collision");
    assert!(executable_error.to_string().contains("conflicts"));
}

#[test]
fn transformed_bundle_limits_accept_exact_boundaries_and_reject_one_over() {
    validate_transformed_bundle_limits(MAX_PRESET_PAYLOAD_FILES, MAX_PRESET_TOTAL_PAYLOAD_BYTES)
        .expect("accept exact transformed bundle limits");

    assert!(validate_transformed_bundle_limits(
        MAX_PRESET_PAYLOAD_FILES.saturating_add(1),
        MAX_PRESET_TOTAL_PAYLOAD_BYTES,
    )
    .is_err());
    assert!(validate_transformed_bundle_limits(
        MAX_PRESET_PAYLOAD_FILES,
        MAX_PRESET_TOTAL_PAYLOAD_BYTES.saturating_add(1),
    )
    .is_err());
}

#[test]
fn transformed_bundle_validation_counts_the_actual_file_inventory() {
    let files = (0..=MAX_PRESET_PAYLOAD_FILES)
        .map(|index| bundle_file(&format!("assets/{index}.png"), Vec::new()))
        .collect::<Vec<_>>();

    assert!(validate_transformed_bundle(&files).is_err());
}
